package me.sourov.quicksale.ui.theme

import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color

// Brand gradient — kept theme-independent so white text/icons stay legible in light & dark.
val BrandGradientStart = Color(0xFF1E4FD0)
val BrandGradientEnd = Color(0xFF0E7C6E)
val BrandGradient = Brush.linearGradient(listOf(BrandGradientStart, BrandGradientEnd))

// Light scheme
val PrimaryLight = Color(0xFF1B5BD6)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFDAE2FF)
val OnPrimaryContainerLight = Color(0xFF001847)
val SecondaryLight = Color(0xFF565E71)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFDAE2F9)
val OnSecondaryContainerLight = Color(0xFF131C2B)
val TertiaryLight = Color(0xFF0F6B5F)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFA6F2E0)
val OnTertiaryContainerLight = Color(0xFF00201C)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFFAF9FD)
val OnBackgroundLight = Color(0xFF1A1B20)
val SurfaceLight = Color(0xFFFAF9FD)
val OnSurfaceLight = Color(0xFF1A1B20)
val SurfaceVariantLight = Color(0xFFE1E2EC)
val OnSurfaceVariantLight = Color(0xFF44474F)
val OutlineLight = Color(0xFF74777F)
val OutlineVariantLight = Color(0xFFC4C6D0)
val SurfaceContainerLight = Color(0xFFEEEDF3)

// Dark scheme
val PrimaryDark = Color(0xFFB1C5FF)
val OnPrimaryDark = Color(0xFF002C71)
val PrimaryContainerDark = Color(0xFF00419F)
val OnPrimaryContainerDark = Color(0xFFDAE2FF)
val SecondaryDark = Color(0xFFBEC6DC)
val OnSecondaryDark = Color(0xFF283141)
val SecondaryContainerDark = Color(0xFF3E4759)
val OnSecondaryContainerDark = Color(0xFFDAE2F9)
val TertiaryDark = Color(0xFF8AD6C4)
val OnTertiaryDark = Color(0xFF003730)
val TertiaryContainerDark = Color(0xFF005047)
val OnTertiaryContainerDark = Color(0xFFA6F2E0)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF111318)
val OnBackgroundDark = Color(0xFFE2E2E9)
val SurfaceDark = Color(0xFF111318)
val OnSurfaceDark = Color(0xFFE2E2E9)
val SurfaceVariantDark = Color(0xFF44474F)
val OnSurfaceVariantDark = Color(0xFFC4C6D0)
val OutlineDark = Color(0xFF8E9099)
val OutlineVariantDark = Color(0xFF44474F)
val SurfaceContainerDark = Color(0xFF1D2024)
