package me.sourov.quicksale.ui.theme

import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color

// Brand gradient — matches the 3ag.ch brand red, kept theme-independent so white text/icons
// stay legible in light & dark.
val BrandGradientStart = Color(0xFFB21310)
val BrandGradientEnd = Color(0xFF87651D)
val BrandGradient = Brush.linearGradient(listOf(BrandGradientStart, BrandGradientEnd))

// Light scheme
val PrimaryLight = Color(0xFFB21310)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFFBD1D0)
val OnPrimaryContainerLight = Color(0xFF2F0504)
val SecondaryLight = Color(0xFF745858)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFE9E2E2)
val OnSecondaryContainerLight = Color(0xFF231A1A)
val TertiaryLight = Color(0xFFA87F24)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFF5EAD1)
val OnTertiaryContainerLight = Color(0xFF32260B)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFFAFAFA)
val OnBackgroundLight = Color(0xFF1C1919)
val SurfaceLight = Color(0xFFFAFAFA)
val OnSurfaceLight = Color(0xFF1C1919)
val SurfaceVariantLight = Color(0xFFE8E3E3)
val OnSurfaceVariantLight = Color(0xFF544545)
val OutlineLight = Color(0xFF8C7373)
val OutlineVariantLight = Color(0xFFD1C7C7)
val SurfaceContainerLight = Color(0xFFF0EFEF)

// Dark scheme
val PrimaryDark = Color(0xFFF7ACAB)
val OnPrimaryDark = Color(0xFF5E0A08)
val PrimaryContainerDark = Color(0xFF8C0F0D)
val OnPrimaryContainerDark = Color(0xFFFBD1D0)
val SecondaryDark = Color(0xFFD8CBCB)
val OnSecondaryDark = Color(0xFF403130)
val SecondaryContainerDark = Color(0xFF604948)
val OnSecondaryContainerDark = Color(0xFFE9E2E2)
val TertiaryDark = Color(0xFFEDD8AB)
val OnTertiaryDark = Color(0xFF5D4614)
val TertiaryContainerDark = Color(0xFF87651D)
val OnTertiaryContainerDark = Color(0xFFF5EAD1)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF181616)
val OnBackgroundDark = Color(0xFFE7E4E4)
val SurfaceDark = Color(0xFF181616)
val OnSurfaceDark = Color(0xFFE7E4E4)
val SurfaceVariantDark = Color(0xFF544545)
val OnSurfaceVariantDark = Color(0xFFD1C7C7)
val OutlineDark = Color(0xFFA38F8F)
val OutlineVariantDark = Color(0xFF544545)
val SurfaceContainerDark = Color(0xFF201D1D)
